In [1]:
# data analysis
import pandas as pd

# split train and test data
from sklearn.model_selection import train_test_split

# Neural Network model
from sklearn.neural_network import MLPClassifier

from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Confusion marix to evaluate the model
from sklearn.metrics import classification_report,confusion_matrix

# Evalute the speed of model
import datetime

# Exportation of  model
import pickle

import winsound

from sklearn.externals import joblib

extracted_data = pd.read_csv(r'C:\Users\User\Desktop\Study\Year 3\Sem 1\CG3002\DanceProject\Machine Learning\extracted data\extracted_dataset.csv')

X = extracted_data.drop(['activity'], axis = 1)
y = extracted_data['activity'].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

start_time = datetime.datetime.now()

mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100, 100, 100, 100, 100, 100), max_iter=1000)
mlp.fit(X_train, y_train)

end_time = datetime.datetime.now()
print("The training accuracy for Neural Network is ", mlp.score(X_train, y_train))
print("The testing accuracy for Neural Network is ", mlp.score(X_test, y_test))
time_taken = end_time - start_time
print("time taken for mlp = ", time_taken)

# start_time = datetime.datetime.now()
# svc = SVC()
# svc.fit(X_train, y_train)
# print("The training accuracy for Support Vector Machines is ", svc.score(X_train, y_train))
# print("The testing accuracy for Support Vector Machines is ", svc.score(X_test, y_test))
# end_time = datetime.datetime.now()
# time_taken = end_time - start_time
# print("time taken for svm = ", time_taken)

start_time = datetime.datetime.now()
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
print("The training accuracy for Random Forestry is ", random_forest.score(X_train, y_train))
print("The testing accuracy for Random Forestry is ", random_forest.score(X_test, y_test))
end_time = datetime.datetime.now()
time_taken = end_time - start_time
print("time taken for rf = ", time_taken)

predictions_mlp = mlp.predict(X_test)
predictions_rf = random_forest.predict(X_test)

print("MLP:")
print(confusion_matrix(y_test, predictions_mlp))
print(classification_report(y_test,predictions_mlp))

print("RF:")
print(confusion_matrix(y_test, random_forest.predict(X_test)))
print(classification_report(y_test, predictions_rf))

# export model
filename_mlp = "Neural_Network_Model.sav"
pickle.dump(mlp, open(filename_mlp, 'wb'))

# filename_svm = "SVM.sav"
# pickle.dump(svc, open(filename_svm, 'wb'))

filename_rd = "RD.sav"
pickle.dump(random_forest, open(filename_rd, 'wb'))

mapping = {1 : 'chicken', 2 : 'number7', 3 : 'sidestep', 4 : 'turnclap', 5 : 'wipers',
           6 : 'numbersix', 7 : 'salute', 8 : 'mermaid', 9 : 'swing', 10 : 'cowboy', 11 : 'finisher'}

print('done')
duration = 800  # millisecond
freq = 500  # Hz
winsound.Beep(freq, duration)

C:\Users\User\Anaconda3_32bit\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


The training accuracy for Neural Network is  0.9725818123341642
The testing accuracy for Neural Network is  0.9741575356626008
time taken for mlp =  0:00:48.165376
The training accuracy for Random Forestry is  0.9928554198876623
The testing accuracy for Random Forestry is  0.9660946867893322
time taken for rf =  0:01:18.048704
MLP:
[[ 176    0    0    0    0    0    0    0    0    0    0    0]
 [   0 1242    2    0    2    1    3    0    0    0    0   13]
 [   0  167 1086    0   15    0    0    0    0    0    0    5]
 [   0    0    0  800    0    0    0    0    0    0    0    0]
 [   0    0    0    0  804    0    0    0    0    0    0    1]
 [   1    0    2    0    3  774    0    0    0    0    0    0]
 [   0    0    0    0    0    0  693    0    0    0    0    0]
 [   0    0    5    2    1    0    0  918    0    0    0    0]
 [   0   14    1    2    4    0    0    0 1051    4    0    0]
 [   0    0    0    0    0    0    0    0    0  675    0    0]
 [   0    0    0    0    1    0    0

In [2]:
import numpy as np
import matplotlib.pyplot as plt
importances = random_forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in random_forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

importance_mean = 0
importance_max = 0
importance_iqr = 0
importance_mad = 0
importance_std = 0

for f in range(X.shape[1]):
    if (indices[f] < 18):
        importance_mean += importances[indices[f]]
    elif (indices[f] < 36):
        importance_max += importances[indices[f]]
    elif (indices[f] < 54):
        importance_iqr += importances[indices[f]]
    elif (indices[f] < 72):
        importance_mad += importances[indices[f]]
    elif (indices[f] < 90):
        importance_std += importances[indices[f]]
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

print("mean: %f" %(importance_mean))
print("max: %f" %(importance_max))
print("iqr: %f" %(importance_iqr))
print("mad: %f" %(importance_mad))
print("median: %f" %(importance_std))

Feature ranking:
1. feature 6 (0.050005)
2. feature 71 (0.048390)
3. feature 0 (0.041725)
4. feature 1 (0.034740)
5. feature 35 (0.031218)
6. feature 69 (0.029668)
7. feature 17 (0.027375)
8. feature 53 (0.026717)
9. feature 18 (0.024729)
10. feature 3 (0.024702)
11. feature 7 (0.023887)
12. feature 46 (0.021854)
13. feature 58 (0.021561)
14. feature 57 (0.020790)
15. feature 4 (0.020370)
16. feature 62 (0.019004)
17. feature 51 (0.018482)
18. feature 19 (0.018170)
19. feature 64 (0.018123)
20. feature 56 (0.018092)
21. feature 45 (0.018059)
22. feature 39 (0.017897)
23. feature 63 (0.017789)
24. feature 44 (0.017496)
25. feature 40 (0.016132)
26. feature 38 (0.015570)
27. feature 34 (0.014961)
28. feature 59 (0.014579)
29. feature 54 (0.013655)
30. feature 28 (0.013430)
31. feature 70 (0.013016)
32. feature 12 (0.012673)
33. feature 33 (0.012081)
34. feature 42 (0.011684)
35. feature 24 (0.011588)
36. feature 66 (0.011492)
37. feature 60 (0.010695)
38. feature 13 (0.010638)
39. featur