In [18]:
# data analysis
import pandas as pd

# split train and test data
from sklearn.model_selection import train_test_split

# Neural Network model
from sklearn.neural_network import MLPClassifier

from sklearn.neural_network import BernoulliRBM

from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Confusion marix to evaluate the model
from sklearn.metrics import classification_report,confusion_matrix

# Evalute the speed of model
import datetime

# Exportation of  model
import pickle

import winsound

from sklearn.externals import joblib

extracted_data = pd.read_csv(r'C:\Users\User\Desktop\Study\Year 3\Sem 1\CG3002\DanceProject\Machine Learning\extracted data\extracted_dataset.csv')

X = extracted_data.drop(['activity'], axis = 1)
y = extracted_data['activity'].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

start_time = datetime.datetime.now()

mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100, 100, 100, 100, 100, 100), max_iter=1000)
mlp.fit(X_train, y_train)

end_time = datetime.datetime.now()
print("The training accuracy for Neural Network is ", mlp.score(X_train, y_train))
print("The testing accuracy for Neural Network is ", mlp.score(X_test, y_test))
time_taken = end_time - start_time
print("time taken for mlp = ", time_taken)

# start_time = datetime.datetime.now()
# svc = SVC()
# svc.fit(X_train, y_train)
# print("The training accuracy for Support Vector Machines is ", svc.score(X_train, y_train))
# print("The testing accuracy for Support Vector Machines is ", svc.score(X_test, y_test))
# end_time = datetime.datetime.now()
# time_taken = end_time - start_time
# print("time taken for svm = ", time_taken)

start_time = datetime.datetime.now()
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
print("The training accuracy for Random Forestry is ", random_forest.score(X_train, y_train))
print("The testing accuracy for Random Forestry is ", random_forest.score(X_test, y_test))
end_time = datetime.datetime.now()
time_taken = end_time - start_time
print("time taken for rf = ", time_taken)

predictions_mlp = mlp.predict(X_test)
predictions_rf = random_forest.predict(X_test)

print("MLP:")
print(confusion_matrix(y_test, predictions_mlp))
print(classification_report(y_test,predictions_mlp))

print("RF:")
print(confusion_matrix(y_test, random_forest.predict(X_test)))
print(classification_report(y_test, predictions_rf))

# export model
filename_mlp = "Neural_Network_Model.sav"
pickle.dump(mlp, open(filename_mlp, 'wb'))

# filename_svm = "SVM.sav"
# pickle.dump(svc, open(filename_svm, 'wb'))

filename_rd = "RD.sav"
pickle.dump(random_forest, open(filename_rd, 'wb'))
# joblib.dump(mlp, filename_mlp)
# joblib.dump(random_forest, filename_rd)

mapping = {1 : 'chicken', 2 : 'number7', 3 : 'sidestep', 4 : 'turnclap', 5 : 'wipers',
           6 : 'numbersix', 7 : 'salute', 8 : 'mermaid', 9 : 'swing', 10 : 'cowboy', 11 : 'finisher'}

print('done')
duration = 800  # millisecond
freq = 500  # Hz
winsound.Beep(freq, duration)

The training accuracy for Neural Network is  0.9940280266100023
The testing accuracy for Neural Network is  0.9930008748906387
time taken for mlp =  0:00:42.040605
The training accuracy for Random Forestry is  1.0
The testing accuracy for Random Forestry is  0.9915010623672041
time taken for rf =  0:00:51.894814
MLP:
[[ 3 13 17 19 22 17 14  7 12  8 12 10]
 [22 83 83 82 80 71 72 61 61 59 73 62]
 [16 95 89 75 93 79 62 60 71 76 60 48]
 [14 76 86 99 84 89 67 66 67 55 68 51]
 [17 74 83 80 71 66 69 49 62 62 70 47]
 [11 85 91 82 87 70 71 64 75 73 62 51]
 [18 68 84 74 41 64 67 49 70 60 63 44]
 [ 7 56 57 68 56 53 41 42 48 46 46 34]
 [16 64 83 66 69 65 59 37 61 53 48 36]
 [16 65 78 69 67 72 64 38 56 53 63 58]
 [12 68 85 59 70 77 61 43 55 67 57 58]
 [ 8 51 51 48 44 57 45 43 40 36 43 30]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       154
          1       0.97      0.98      0.98       809
          2       0.97      0.97      0.97       824

In [19]:
import numpy as np
import matplotlib.pyplot as plt
importances = random_forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in random_forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

importance_mean = 0
importance_max = 0
importance_iqr = 0
importance_mad = 0
importance_std = 0

for f in range(X.shape[1]):
    if (indices[f] < 18):
        importance_mean += importances[indices[f]]
    elif (indices[f] < 36):
        importance_max += importances[indices[f]]
    elif (indices[f] < 54):
        importance_iqr += importances[indices[f]]
    elif (indices[f] < 72):
        importance_mad += importances[indices[f]]
    elif (indices[f] < 90):
        importance_std += importances[indices[f]]
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

print("mean: %f" %(importance_mean))
print("max: %f" %(importance_max))
print("iqr: %f" %(importance_iqr))
print("mad: %f" %(importance_mad))
print("std: %f" %(importance_std))

Feature ranking:
1. feature 6 (0.044223)
2. feature 71 (0.043480)
3. feature 0 (0.037834)
4. feature 3 (0.031414)
5. feature 1 (0.029424)
6. feature 53 (0.029170)
7. feature 17 (0.027567)
8. feature 7 (0.026130)
9. feature 62 (0.025500)
10. feature 40 (0.025381)
11. feature 35 (0.025351)
12. feature 44 (0.025289)
13. feature 18 (0.022821)
14. feature 45 (0.022434)
15. feature 64 (0.021858)
16. feature 4 (0.021740)
17. feature 69 (0.020390)
18. feature 46 (0.020048)
19. feature 57 (0.019906)
20. feature 70 (0.018853)
21. feature 58 (0.018463)
22. feature 38 (0.017620)
23. feature 19 (0.017129)
24. feature 59 (0.016082)
25. feature 51 (0.015713)
26. feature 56 (0.015505)
27. feature 39 (0.015426)
28. feature 63 (0.015222)
29. feature 24 (0.014290)
30. feature 66 (0.014120)
31. feature 54 (0.013894)
32. feature 28 (0.013711)
33. feature 41 (0.013493)
34. feature 12 (0.013103)
35. feature 52 (0.013027)
36. feature 22 (0.011132)
37. feature 49 (0.010963)
38. feature 48 (0.010873)
39. featur