In [6]:
# data analysis
import pandas as pd

# split train and test data
from sklearn.model_selection import train_test_split

# Neural Network model
from sklearn.neural_network import MLPClassifier

from sklearn.neural_network import BernoulliRBM

from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Confusion marix to evaluate the model
from sklearn.metrics import classification_report,confusion_matrix

# Evalute the speed of model
import datetime

# Exportation of  model
import pickle

import winsound

from sklearn.externals import joblib

extracted_data = pd.read_csv(r'C:\Users\User\Desktop\Study\Year 3\Sem 1\CG3002\DanceProject\Machine Learning\extracted data\extracted_dataset.csv')

X = extracted_data.drop(['activity'], axis = 1)
y = extracted_data['activity'].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

start_time = datetime.datetime.now()

mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100, 100, 100, 100, 100, 100), max_iter=1000)
mlp.fit(X_train, y_train)

end_time = datetime.datetime.now()
print("The training accuracy for Neural Network is ", mlp.score(X_train, y_train))
print("The testing accuracy for Neural Network is ", mlp.score(X_test, y_test))
time_taken = end_time - start_time
print("time taken for mlp = ", time_taken)

# start_time = datetime.datetime.now()
# svc = SVC()
# svc.fit(X_train, y_train)
# print("The training accuracy for Support Vector Machines is ", svc.score(X_train, y_train))
# print("The testing accuracy for Support Vector Machines is ", svc.score(X_test, y_test))
# end_time = datetime.datetime.now()
# time_taken = end_time - start_time
# print("time taken for svm = ", time_taken)

start_time = datetime.datetime.now()
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
print("The training accuracy for Random Forestry is ", random_forest.score(X_train, y_train))
print("The testing accuracy for Random Forestry is ", random_forest.score(X_test, y_test))
end_time = datetime.datetime.now()
time_taken = end_time - start_time
print("time taken for rf = ", time_taken)

predictions_mlp = mlp.predict(X_test)
predictions_rf = random_forest.predict(X_test)

print("MLP:")
print(confusion_matrix(y_test, predictions_mlp))
print(classification_report(y_test,predictions_mlp))

print("RF:")
print(confusion_matrix(y_test, random_forest.predict(X_test)))
print(classification_report(y_test, predictions_rf))

# export model
filename_mlp = "Neural_Network_Model.sav"
pickle.dump(mlp, open(filename_mlp, 'wb'))

# filename_svm = "SVM.sav"
# pickle.dump(svc, open(filename_svm, 'wb'))

filename_rd = "RD.sav"
pickle.dump(random_forest, open(filename_rd, 'wb'))

mapping = {1 : 'chicken', 2 : 'number7', 3 : 'sidestep', 4 : 'turnclap', 5 : 'wipers',
           6 : 'numbersix', 7 : 'salute', 8 : 'mermaid', 9 : 'swing', 10 : 'cowboy', 11 : 'finisher'}

print('done')
duration = 800  # millisecond
freq = 500  # Hz
winsound.Beep(freq, duration)

The training accuracy for Neural Network is  0.9881913356128168
The testing accuracy for Neural Network is  0.9881569207994079
time taken for mlp =  0:03:26.683410
The training accuracy for Random Forestry is  1.0
The testing accuracy for Random Forestry is  0.977688484720313
time taken for rf =  0:01:27.890979
MLP:
[[ 150    0    0    0    0    0    0    0    0    0    0    0]
 [   0 1118  101    0    0    0    0    0    1    0    0    0]
 [   0    1 1204    0    0    0    0    0    0    0    0    0]
 [   1    0    2  803    0    0    0    0    0    0    0    0]
 [   0    0    0    0  749    0    0    0    0    0    0    0]
 [   0    0    0    0    0  812    0    0    0    0    0    0]
 [   0    0    0    0    0    0  695    0    0    0    0    0]
 [   0    0    6    0    0    0    0  871    0    0    0    0]
 [   0    0    0    0    0    0    0    0 1041    0    0    0]
 [   0    0    0    0    0    0    0    0    0  669    0    0]
 [   0    0    0    0    0    0    0    0    0    0 

In [7]:
import numpy as np
import matplotlib.pyplot as plt
importances = random_forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in random_forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

importance_mean = 0
importance_max = 0
importance_iqr = 0
importance_mad = 0
importance_std = 0

for f in range(X.shape[1]):
    if (indices[f] < 18):
        importance_mean += importances[indices[f]]
    elif (indices[f] < 36):
        importance_max += importances[indices[f]]
    elif (indices[f] < 54):
        importance_iqr += importances[indices[f]]
    elif (indices[f] < 72):
        importance_mad += importances[indices[f]]
    elif (indices[f] < 90):
        importance_std += importances[indices[f]]
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

print("mean: %f" %(importance_mean))
print("max: %f" %(importance_max))
print("iqr: %f" %(importance_iqr))
print("mad: %f" %(importance_mad))
print("median: %f" %(importance_std))

Feature ranking:
1. feature 6 (0.056817)
2. feature 0 (0.047357)
3. feature 35 (0.035165)
4. feature 1 (0.033430)
5. feature 71 (0.031428)
6. feature 17 (0.030776)
7. feature 3 (0.029086)
8. feature 69 (0.027480)
9. feature 64 (0.025140)
10. feature 53 (0.024577)
11. feature 33 (0.021420)
12. feature 28 (0.020393)
13. feature 57 (0.020334)
14. feature 58 (0.018640)
15. feature 22 (0.018184)
16. feature 4 (0.018041)
17. feature 26 (0.018039)
18. feature 46 (0.018039)
19. feature 20 (0.017684)
20. feature 44 (0.017418)
21. feature 21 (0.016980)
22. feature 23 (0.016050)
23. feature 62 (0.015983)
24. feature 59 (0.015562)
25. feature 7 (0.014878)
26. feature 56 (0.014063)
27. feature 40 (0.013879)
28. feature 70 (0.013235)
29. feature 63 (0.013120)
30. feature 12 (0.012938)
31. feature 9 (0.012578)
32. feature 27 (0.012108)
33. feature 38 (0.011967)
34. feature 34 (0.011498)
35. feature 30 (0.011206)
36. feature 13 (0.011183)
37. feature 45 (0.011119)
38. feature 66 (0.010909)
39. feature