In [3]:
# data analysis
import pandas as pd

# split train and test data
from sklearn.model_selection import train_test_split

# Neural Network model
from sklearn.neural_network import MLPClassifier

from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Confusion marix to evaluate the model
from sklearn.metrics import classification_report,confusion_matrix

# Evalute the speed of model
import datetime

# Exportation of  model
import pickle

import winsound

from sklearn.externals import joblib

extracted_data = pd.read_csv(r'C:\Users\User\Desktop\Study\Year 3\Sem 1\CG3002\DanceProject\Machine Learning\extracted data\extracted_dataset.csv')

X = extracted_data.drop(['activity'], axis = 1)
y = extracted_data['activity'].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

start_time = datetime.datetime.now()

mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100, 100, 100, 100, 100, 100), max_iter=1000)
mlp.fit(X_train, y_train)

end_time = datetime.datetime.now()
print("The training accuracy for Neural Network is ", mlp.score(X_train, y_train))
print("The testing accuracy for Neural Network is ", mlp.score(X_test, y_test))
time_taken = end_time - start_time
print("time taken for mlp = ", time_taken)

# start_time = datetime.datetime.now()
# svc = SVC()
# svc.fit(X_train, y_train)
# print("The training accuracy for Support Vector Machines is ", svc.score(X_train, y_train))
# print("The testing accuracy for Support Vector Machines is ", svc.score(X_test, y_test))
# end_time = datetime.datetime.now()
# time_taken = end_time - start_time
# print("time taken for svm = ", time_taken)

start_time = datetime.datetime.now()
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
print("The training accuracy for Random Forestry is ", random_forest.score(X_train, y_train))
print("The testing accuracy for Random Forestry is ", random_forest.score(X_test, y_test))
end_time = datetime.datetime.now()
time_taken = end_time - start_time
print("time taken for rf = ", time_taken)

predictions_mlp = mlp.predict(X_test)
predictions_rf = random_forest.predict(X_test)

print("MLP:")
print(confusion_matrix(y_test, predictions_mlp))
print(classification_report(y_test,predictions_mlp))

print("RF:")
print(confusion_matrix(y_test, random_forest.predict(X_test)))
print(classification_report(y_test, predictions_rf))

# export model
filename_mlp = "Neural_Network_Model.sav"
pickle.dump(mlp, open(filename_mlp, 'wb'))

# filename_svm = "SVM.sav"
# pickle.dump(svc, open(filename_svm, 'wb'))

filename_rd = "RD.sav"
pickle.dump(random_forest, open(filename_rd, 'wb'))

mapping = {1 : 'chicken', 2 : 'number7', 3 : 'sidestep', 4 : 'turnclap', 5 : 'wipers',
           6 : 'numbersix', 7 : 'salute', 8 : 'mermaid', 9 : 'swing', 10 : 'cowboy', 11 : 'finisher'}

print('done')
duration = 800  # millisecond
freq = 500  # Hz
winsound.Beep(freq, duration)

The training accuracy for Neural Network is  0.9759703189790832
The testing accuracy for Neural Network is  0.974881124664048
time taken for mlp =  0:00:32.230618
The training accuracy for Random Forestry is  0.9927635281820375
The testing accuracy for Random Forestry is  0.9641306594996899
time taken for rf =  0:01:32.864387
MLP:
[[ 159    0    0    0    0    0    0    0    0    0    0    0]
 [   0 1140  121    0    0    0    0    0    0    0    0    0]
 [   0   64 1177    0   13    0    1    6    0    0    0    0]
 [   0    0    0  835    4    0    0    2    0    0    0    1]
 [   0    0    0    0  768    0    0    0    0    0    0    0]
 [   1    0    0    0    1  833    0    0    0    0    0    0]
 [   0    0    0    0    0    0  678    0    0    0    0    0]
 [   0    0   10    0    2    0    0  992    0    0    1    0]
 [   0    1    1    0    0    0    0    0 1022    0    0    0]
 [   0    0    0    0    0    0    0    0    0  654    0    0]
 [   0    0    0    0    1    0    0 

In [4]:
import numpy as np
import matplotlib.pyplot as plt
importances = random_forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in random_forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

importance_mean = 0
importance_max = 0
importance_iqr = 0
importance_mad = 0
importance_std = 0

for f in range(X.shape[1]):
    if (indices[f] < 18):
        importance_mean += importances[indices[f]]
    elif (indices[f] < 36):
        importance_max += importances[indices[f]]
    elif (indices[f] < 54):
        importance_iqr += importances[indices[f]]
    elif (indices[f] < 72):
        importance_mad += importances[indices[f]]
    elif (indices[f] < 90):
        importance_std += importances[indices[f]]
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

print("mean: %f" %(importance_mean))
print("max: %f" %(importance_max))
print("iqr: %f" %(importance_iqr))
print("mad: %f" %(importance_mad))
print("median: %f" %(importance_std))

Feature ranking:
1. feature 6 (0.041479)
2. feature 71 (0.032173)
3. feature 0 (0.031228)
4. feature 89 (0.030906)
5. feature 3 (0.028306)
6. feature 1 (0.026690)
7. feature 35 (0.025532)
8. feature 53 (0.024313)
9. feature 17 (0.023405)
10. feature 69 (0.021941)
11. feature 82 (0.021911)
12. feature 18 (0.019541)
13. feature 19 (0.019255)
14. feature 7 (0.019204)
15. feature 75 (0.017227)
16. feature 57 (0.016881)
17. feature 87 (0.016425)
18. feature 64 (0.016370)
19. feature 76 (0.015727)
20. feature 39 (0.015508)
21. feature 74 (0.015016)
22. feature 44 (0.014882)
23. feature 51 (0.014820)
24. feature 58 (0.014662)
25. feature 4 (0.014355)
26. feature 77 (0.014115)
27. feature 80 (0.014049)
28. feature 62 (0.013737)
29. feature 45 (0.013265)
30. feature 24 (0.013212)
31. feature 12 (0.012865)
32. feature 63 (0.012359)
33. feature 59 (0.011517)
34. feature 46 (0.011297)
35. feature 28 (0.011260)
36. feature 81 (0.011221)
37. feature 70 (0.010935)
38. feature 56 (0.010810)
39. featur